# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-24 12:20
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_countries.fields
import shuup.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shuup_shipping_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressShippingRegion',
            fields=[
                ('shippingregion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shuup_shipping_table.ShippingRegion')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='country')),
                ('region', models.TextField(blank=True, help_text='use comma-separated values to match several names', null=True, verbose_name='region')),
                ('city', models.TextField(blank=True, help_text='use comma-separated values to match several names', null=True, verbose_name='city')),
                ('street1', models.TextField(blank=True, help_text='use comma-separated values to match several names', null=True, verbose_name='street (1)')),
                ('street2', models.TextField(blank=True, help_text='use comma-separated values to match several names', null=True, verbose_name='street (2)')),
                ('street3', models.TextField(blank=True, help_text='use comma-separated values to match several names', null=True, verbose_name='street (3)')),
            ],
            options={
                'verbose_name': 'shipping region by address',
                'verbose_name_plural': 'shipping regions by address',
            },
            bases=('shuup_shipping_table.shippingregion',),
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='countryshippingregion',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='postalcoderangeshippingregion',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='shippingregion',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='shippingtablebymodebehaviorcomponent',
            name='cubic_weight_exemption',
            field=shuup.core.fields.MeasurementField(decimal_places=3, default=Decimal('0'), help_text='The Cubic Weight will be considered if the sum of all products real weights is higher then this value.', max_digits=8, unit='kg', verbose_name='Cubic Weight exemption value (kg)'),
        ),
        migrations.AddField(
            model_name='shippingtablebymodebehaviorcomponent',
            name='cubic_weight_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('6000'), help_text="Google it if you don't know what you're doing.", max_digits=10, verbose_name='Cubic Weight Factor (cm³)'),
        ),
        migrations.AddField(
            model_name='shippingtablebymodebehaviorcomponent',
            name='max_package_edges_sum',
            field=shuup.core.fields.MeasurementField(decimal_places=2, default=Decimal('0'), help_text='The max sum of width, height and length of the package. This is only used for Cubic Weight method since the order/basket will be splitted into packages for volume calculation.', max_digits=7, unit='mm', verbose_name='Max package edge sum (mm)'),
        ),
        migrations.AddField(
            model_name='shippingtablebymodebehaviorcomponent',
            name='max_package_height',
            field=shuup.core.fields.MeasurementField(decimal_places=2, default=Decimal('0'), help_text='This is only used for Cubic Weight method since the order/basket will be splitted into packages for volume calculation.', max_digits=7, unit='mm', verbose_name='Max package height (mm)'),
        ),
        migrations.AddField(
            model_name='shippingtablebymodebehaviorcomponent',
            name='max_package_length',
            field=shuup.core.fields.MeasurementField(decimal_places=2, default=Decimal('0'), help_text='This is only used for Cubic Weight method since the order/basket will be splitted into packages for volume calculation.', max_digits=7, unit='mm', verbose_name='Max package length (mm)'),
        ),
        migrations.AddField(
            model_name='shippingtablebymodebehaviorcomponent',
            name='max_package_weight',
            field=shuup.core.fields.MeasurementField(decimal_places=3, default=Decimal('0'), help_text='This is only used for Cubic Weight method since the order/basket will be splitted into packages for volume calculation.', max_digits=8, unit='kg', verbose_name='Max package weight (kg)'),
        ),
        migrations.AddField(
            model_name='shippingtablebymodebehaviorcomponent',
            name='max_package_width',
            field=shuup.core.fields.MeasurementField(decimal_places=2, default=Decimal('0'), help_text='This is only used for Cubic Weight method since the order/basket will be splitted into packages for volume calculation.', max_digits=7, unit='mm', verbose_name='Max package width (mm)'),
        ),
        migrations.AddField(
            model_name='shippingtablebymodebehaviorcomponent',
            name='use_cubic_weight',
            field=models.BooleanField(default=False, help_text='Enable this to calculate the cubic weight and use the heaviest measurement (real weight or cubic weight).', verbose_name='Use Cubic Weight'),
        ),
        migrations.AddField(
            model_name='specificshippingtablebehaviorcomponent',
            name='cubic_weight_exemption',
            field=shuup.core.fields.MeasurementField(decimal_places=3, default=Decimal('0'), help_text='The Cubic Weight will be considered if the sum of all products real weights is higher then this value.', max_digits=8, unit='kg', verbose_name='Cubic Weight exemption value (kg)'),
        ),
        migrations.AddField(
            model_name='specificshippingtablebehaviorcomponent',
            name='cubic_weight_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('6000'), help_text="Google it if you don't know what you're doing.", max_digits=10, verbose_name='Cubic Weight Factor (cm³)'),
        ),
        migrations.AddField(
            model_name='specificshippingtablebehaviorcomponent',
            name='max_package_edges_sum',
            field=shuup.core.fields.MeasurementField(decimal_places=2, default=Decimal('0'), help_text='The max sum of width, height and length of the package. This is only used for Cubic Weight method since the order/basket will be splitted into packages for volume calculation.', max_digits=7, unit='mm', verbose_name='Max package edge sum (mm)'),
        ),
        migrations.AddField(
            model_name='specificshippingtablebehaviorcomponent',
            name='max_package_height',
            field=shuup.core.fields.MeasurementField(decimal_places=2, default=Decimal('0'), help_text='This is only used for Cubic Weight method since the order/basket will be splitted into packages for volume calculation.', max_digits=7, unit='mm', verbose_name='Max package height (mm)'),
        ),
        migrations.AddField(
            model_name='specificshippingtablebehaviorcomponent',
            name='max_package_length',
            field=shuup.core.fields.MeasurementField(decimal_places=2, default=Decimal('0'), help_text='This is only used for Cubic Weight method since the order/basket will be splitted into packages for volume calculation.', max_digits=7, unit='mm', verbose_name='Max package length (mm)'),
        ),
        migrations.AddField(
            model_name='specificshippingtablebehaviorcomponent',
            name='max_package_weight',
            field=shuup.core.fields.MeasurementField(decimal_places=3, default=Decimal('0'), help_text='This is only used for Cubic Weight method since the order/basket will be splitted into packages for volume calculation.', max_digits=8, unit='kg', verbose_name='Max package weight (kg)'),
        ),
        migrations.AddField(
            model_name='specificshippingtablebehaviorcomponent',
            name='max_package_width',
            field=shuup.core.fields.MeasurementField(decimal_places=2, default=Decimal('0'), help_text='This is only used for Cubic Weight method since the order/basket will be splitted into packages for volume calculation.', max_digits=7, unit='mm', verbose_name='Max package width (mm)'),
        ),
        migrations.AddField(
            model_name='specificshippingtablebehaviorcomponent',
            name='use_cubic_weight',
            field=models.BooleanField(default=False, help_text='Enable this to calculate the cubic weight and use the heaviest measurement (real weight or cubic weight).', verbose_name='Use Cubic Weight'),
        ),
    ]
